### PR TITLE
listen on UNIX Domain Sockets (UDS) instead of TCP

### PR DESCRIPTION
**Pull request by stapelberg**
This removes any need for passwords, which makes the DSN more stable.

related to issue #3

### CODE REVIEW

**Comment by stapelberg** [comment]
(Successful GitHub Actions run on Mac, Linux and Windows: https://github.com/stapelberg/postgrestest/actions/runs/12285379176/job/34283230638)

**Review by zombiezen — APPROVED** [review]
LGTM! Thank you so much! 🎉

**Comment by zombiezen** [comment]
Now that this is merged, is everything deterministic? Or is there remaining work? (I noticed you used "related to" instead of "fixes" in regards to #3.)

**Comment by stapelberg** [comment]
> Now that this is merged, is everything deterministic? Or is there remaining work? (I noticed you used "related to" instead of "fixes" in regards to #3.)

There is remaining work: The directory is currently a temporary directory without a deterministic name. In my version, I am solving that by making the directory configurable: https://github.com/zombiezen/postgrestest/commit/579e3605a3aca17600715aa921cf1c2925471e44

I can send that PR, too, but it currently is dependent on https://github.com/zombiezen/postgrestest/commit/da709cd15c616a4e7227f644d12f07ae97c0890f for the functional option pattern. I can send that PR first, unless you have a different preference…?

BTW, After both PRs are merged, there is only one commit of difference between this upstream repository and my repository, so maybe I can delete my repository eventually :)

**Comment by zombiezen** [comment]
> There is remaining work: The directory is currently a temporary directory without a deterministic name. In my version, I am solving that by making the directory configurable: [579e360](https://github.com/zombiezen/postgrestest/commit/579e3605a3aca17600715aa921cf1c2925471e44)
> 
> I can send that PR, too, but it currently is dependent on [da709cd](https://github.com/zombiezen/postgrestest/commit/da709cd15c616a4e7227f644d12f07ae97c0890f) for the functional option pattern. I can send that PR first, unless you have a different preference…?

That sounds good. I would prefer using an options struct rather than functional options, but other than that, seems like a straightforward change to merge.

> BTW, After both PRs are merged, there is only one commit of difference between this upstream repository and my repository, so maybe I can delete my repository eventually :)

Oh interesting! I'll have to look more closely when I have a moment.

**Pull request merged**
